[versions]
agp = "8.3.2"
androidImageCropper = "4.6.0"
circleimageview = "3.1.0"
cloudinaryAndroid = "3.0.2"
commonsIo = "2.13.0"
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.7.0"
material = "1.0.0"
parseVersion = "4.3.0"
retrofit = "2.11.0"
appcompat = "1.6.1"
navigation = "2.7.7"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
cloudinary-android = { module = "com.cloudinary:cloudinary-android", version.ref = "cloudinaryAndroid" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
material = { module = "com.google.android.material:material", version.ref = "material" }
parse-sdk-android-parse = { module = "com.github.parse-community.Parse-SDK-Android:parse", version.ref = "parseVersion" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
picasso = { group = "com.squareup.picasso", name = "picasso", version = "2.8" }
vanniktech-android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }